"""empty message

Revision ID: a8d464e18b52
Revises: 502693a4d106
Create Date: 2020-04-30 21:58:40.369967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d464e18b52'
down_revision = '502693a4d106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cw_contact',
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('contype', sa.String(length=10), nullable=True),
    sa.Column('conway', sa.String(length=20), nullable=True),
    sa.Column('phoneno', sa.Integer(), nullable=True),
    sa.Column('hyperlink', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('conid')
    )
    op.drop_table('sqlite_sequence')
    op.alter_column('cw_cinemas', 'c_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'cw_cinemas', ['c_address'])
    op.create_unique_constraint(None, 'cw_cinemas', ['c_name'])
    op.alter_column('cw_movie', 'm_category',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('cw_movie', 'm_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cw_movie', 'm_unreleased',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cw_movie', 'tid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('cw_movie_m_name_uindex', table_name='cw_movie')
    op.drop_index('cw_movie_m_num_uindex', table_name='cw_movie')
    op.drop_index('cw_movie_mid_uindex', table_name='cw_movie')
    op.drop_index('cw_movie_tid_uindex', table_name='cw_movie')
    op.create_unique_constraint(None, 'cw_movie', ['m_name'])
    op.drop_constraint(None, 'cw_movie', type_='foreignkey')
    op.create_foreign_key(None, 'cw_movie', 'cw_ticket', ['tid'], ['tid'])
    op.alter_column('cw_price', 'p_person',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cw_price', 'tid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('cw_price_pid_uindex', table_name='cw_price')
    op.drop_index('cw_price_tid_uindex', table_name='cw_price')
    op.alter_column('cw_ticket', 'c_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cw_ticket', 'm_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cw_ticket', 'p_person',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('cw_ticket_c_num_uindex', table_name='cw_ticket')
    op.drop_index('cw_ticket_m_num_uindex', table_name='cw_ticket')
    op.drop_index('cw_ticket_tid_uindex', table_name='cw_ticket')
    op.alter_column('cw_user', 'u_phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'cw_user', ['u_email'])
    op.create_unique_constraint(None, 'cw_user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cw_user', type_='unique')
    op.drop_constraint(None, 'cw_user', type_='unique')
    op.alter_column('cw_user', 'u_phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('cw_ticket_tid_uindex', 'cw_ticket', ['tid'], unique=1)
    op.create_index('cw_ticket_m_num_uindex', 'cw_ticket', ['m_num'], unique=1)
    op.create_index('cw_ticket_c_num_uindex', 'cw_ticket', ['c_num'], unique=1)
    op.alter_column('cw_ticket', 'p_person',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cw_ticket', 'm_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cw_ticket', 'c_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('cw_price_tid_uindex', 'cw_price', ['tid'], unique=1)
    op.create_index('cw_price_pid_uindex', 'cw_price', ['pid'], unique=1)
    op.alter_column('cw_price', 'tid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cw_price', 'p_person',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'cw_movie', type_='foreignkey')
    op.create_foreign_key(None, 'cw_movie', 'cw_ticket', ['mid', 'tid'], ['tid', 'tid'])
    op.drop_constraint(None, 'cw_movie', type_='unique')
    op.create_index('cw_movie_tid_uindex', 'cw_movie', ['tid'], unique=1)
    op.create_index('cw_movie_mid_uindex', 'cw_movie', ['mid'], unique=1)
    op.create_index('cw_movie_m_num_uindex', 'cw_movie', ['m_num'], unique=1)
    op.create_index('cw_movie_m_name_uindex', 'cw_movie', ['m_name'], unique=1)
    op.alter_column('cw_movie', 'tid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cw_movie', 'm_unreleased',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cw_movie', 'm_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cw_movie', 'm_category',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_constraint(None, 'cw_cinemas', type_='unique')
    op.drop_constraint(None, 'cw_cinemas', type_='unique')
    op.alter_column('cw_cinemas', 'c_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('cw_contact')
    # ### end Alembic commands ###
