"""empty message

Revision ID: ca74e5ff74e2
Revises: 24c91e397d2d
Create Date: 2020-04-19 00:43:46.690956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca74e5ff74e2'
down_revision = '24c91e397d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cw_cinemas',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=50), nullable=True),
    sa.Column('c_district', sa.String(length=50), nullable=True),
    sa.Column('c_address', sa.String(length=250), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['cw_facility.fid'], ),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('c_address'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('cw_facility',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('total_house', sa.Integer(), nullable=False),
    sa.Column('total_seat', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cw_cinemas.cid'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('cw_reports',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('r_email', sa.String(length=150), nullable=False),
    sa.Column('r_phone', sa.Integer(), nullable=False),
    sa.Column('r_category', sa.String(length=50), nullable=True),
    sa.Column('r_title', sa.String(length=100), nullable=True),
    sa.Column('r_body', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cw_user.id'], ),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('r_email')
    )
    op.drop_table('sqlite_sequence')
    op.alter_column('cw_user', 'u_phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'cw_user', ['username'])
    op.create_unique_constraint(None, 'cw_user', ['u_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cw_user', type_='unique')
    op.drop_constraint(None, 'cw_user', type_='unique')
    op.alter_column('cw_user', 'u_phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('cw_reports')
    op.drop_table('cw_facility')
    op.drop_table('cw_cinemas')
    # ### end Alembic commands ###
